# clock_recognizer----------------------------------------------------------------

INPUT_IMG_PATH: './cocome'
IMG_SAVE_PATH: './rec'
INFERENCE_SAVE_PATH: './rec/inference_result'
MASK_SAVE_PATH: './rec/mask_result'
ADJUST_SAVE_PATH: './rec/adjust_result'
FIT_SAVE_PATH: './rec/fit_result'
PARAM_SAVE_PATH: './rec/param'

MODEL_CONFIG: './configs/myConfigs/pointer_config.py'
CHECKPOINT: './checkpoints/new.pth'

# corner point (cv2.goodFeaturesToTrack)
QUALITY_LEVEL: 0.01
BLOCK_SIZE: 100
MAX_CORNERS: 2
MIN_DISTANCE: 289

# perspective rectangle w,h
# o-----------> w
# |
# |
# |
# |
# v
# h

REC:
  EAST:
    - 800
    - 500
  SOUTH:
    - 500
    - 800
  WEST:
    - 200
    - 500
  NORTH:
    - 500
    - 200
  SIZE:
    - 1000
    - 1000

# fit circle
SAMPLE_DIST_TO_CORNER: 100
SAMPLE_INDEX: 47

# color
RGBCOLOR_CYAN: 
  - 255
  - 255
  - 0

RGBCOLOR_BLUE:
  - 255
  - 0
  - 0

RGBCOLOR_YELLOW:
  - 0
  - 255
  - 255

RGBCOLOR_RED:
  - 0
  - 0
  - 255

RGBCOLOR_ORANGE:
  - 0
  - 165
  - 255

# ocr_recognizer ---------------------------------------------------------

OCR_IMG_SAVE_PATH: './ocr/visualize'
OCR_FILE_SAVE_PATH: './ocr/result'

# ocr _preProcess
MORPHOLOGY_KERNEL_SIZE: 2
MORPHOLOGY_KERNEL_ITERATION: 3

# ocr _postProcess
ACC_THRESH: 0.6

# result_calculator ------------------------------------------------------
MIN_DEGREE: 25
MAX_DEGREE: 335
MIN_R_FACTOR: 0.5

RANSAC_EPOCH: 1000
RANSAC_SIGMA: 0.01
RANSAC_P: 0.95









# debug
SHOW_IMG: false